### ISSUE TITLE
Add Parquet Conversion

### ISSUE THREAD

**Issue by Saldef** [CSS-Electronics/mdf4-converters#8]
Could you add support to convert `mdf4` to `parquet`? as it is really important for people working with Spark. 

I know `asammdf` has the ability to convert to `parquet` but sometimes it doesn't work, and it is nice to have second open-source alternative when `asammdf` stops working. 

Thanks in advance

**Comment by MatinF** [comment]
Hi there, thanks for the suggestion. We do not currently have plans to support a parquet output. However, the library is open source so if you do create a version for this use case, we can of course review and potentially include it in the master.

You are also welcome to share more details on your use case by contacting us via our contact form. It sounds interesting how you'd use spark for visualization of the CANedge data.

**Comment by dapperfu** [comment]
I've used parquet files as an intermediate for Dask data analysis.

In my case I converted to socketcan -> pandas dataframe -> saved parquet.

A short script with CSV -> pandas -> parquet should work in most cases.

**Comment by MatinF** [comment]
Thanks, we'll consider this. Our aim is to potentially add Dask support natively in our Python API at some point. I think the Python API would be the simplest way to solve this in the meanwhile as well, since you can load the raw/decode data into pandas dataframes quite easily, then export/process the data as you'd prefer.

Closing this, though feel free to send us a mail via our contact form to discuss further - would like to understand these use cases in more detail to learn how we can best serve 'bigger data' processing use cases.
